# Application makefile

# Command name (Public function 'int <APPNAME>_main(void)' required)
APPNAME = lte_at_cmd

# Application execute priority (Range: 0 ~ 255, Default: 100)
PRIORITY =

# Application stack memory size (Default: 2048)
STACKSIZE =

# Main source code
MAINSRC = lte_at_cmd_main.cxx

# Additional C source files (*.c)
CSRCS =

# Additional C++ source files (*.cxx)
CXXSRCS =

# Additional assembler source files (*.S)
ASRCS =

# C compiler flags
CFLAGS =

# C++ compiler flags
CXXFLAGS =

include $(SPRESENSE_HOME)/.vscode/application.mk
